// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJs3rDMWGhbgxUIfSYABO73ZuJ471yrfg',
    appId: '1:1053091388475:web:32a5297f1d4b1b37bc901e',
    messagingSenderId: '1053091388475',
    projectId: 'knock-111f7',
    authDomain: 'knock-111f7.firebaseapp.com',
    storageBucket: 'knock-111f7.appspot.com',
    measurementId: 'G-XKP9CK30PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIQ8gviJD11FIJAMvnzDBkYeQykJUH5Vc',
    appId: '1:1053091388475:android:2ed642e1b9fd8702bc901e',
    messagingSenderId: '1053091388475',
    projectId: 'knock-111f7',
    storageBucket: 'knock-111f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_v8KjN2RSVrla1YLOYX6AGxOYkMpm5ks',
    appId: '1:1053091388475:ios:94854fc93133c5a0bc901e',
    messagingSenderId: '1053091388475',
    projectId: 'knock-111f7',
    storageBucket: 'knock-111f7.appspot.com',
    iosBundleId: 'com.example.knockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_v8KjN2RSVrla1YLOYX6AGxOYkMpm5ks',
    appId: '1:1053091388475:ios:94854fc93133c5a0bc901e',
    messagingSenderId: '1053091388475',
    projectId: 'knock-111f7',
    storageBucket: 'knock-111f7.appspot.com',
    iosBundleId: 'com.example.knockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJs3rDMWGhbgxUIfSYABO73ZuJ471yrfg',
    appId: '1:1053091388475:web:00a834325da065bfbc901e',
    messagingSenderId: '1053091388475',
    projectId: 'knock-111f7',
    authDomain: 'knock-111f7.firebaseapp.com',
    storageBucket: 'knock-111f7.appspot.com',
    measurementId: 'G-4C227MX71X',
  );
}
